### ISSUE TITLE
速度問題

### ISSUE THREAD

**Issue by shadowjohn** [drunkwcodes/bb7#1]
感謝您的分享，不過 readme 裡有地方建議調整

1. pipx install bb7=0.3.3  → pipx install bb7==0.3.3  少一個 =
2. requires-python = ">=3.11" → requires-python = ">=3.10"   ,  3.10 以後應該都可以
3. 建議補上允許防火牆 port 11434 雖然不是 bb7 的問題， iptables -I INPUT -p tcp -s 127.0.0.1/24 --dport 11434 -j ACCEPT
4. 運作妹叮妹噹，不知道是不是顯卡太差，跑到 timeout

![image](https://github.com/user-attachments/assets/50f84a10-2161-48a0-97e9-3a4a92de63f2)
![image](https://github.com/user-attachments/assets/2b4486ae-c6d8-49d2-a751-22931e451184)

**Comment by drunkwcodes** [comment]
謝謝你的反饋，在這逐項回覆：

1. 已修正
2. 3.11 是我的偏愛，但也修正了
3. 謝謝建議，不過 ollama repo 好像也沒有這方面的說明，若之後有人遇到此問題會另外開 wiki 補充
4. 說不定可以試用 llama3.2:1b 看看，犧牲一點對話品質換取回應速度。
